services:
  server:
    build: # build from local Dockerfile
      context: ../iztg-bedrock-server
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT:-19132}:19132/udp"
      - "${HOST_PORT_V6:-19133}:19133/udp"
    environment:
      EULA: "TRUE"
      VERSION: "${VERSION:-latest}"
      SERVER_NAME: "${SERVER_NAME:-Bedrock Server}"
      GAMEMODE: "${GAMEMODE:-creative}"
      FORCE_GAMEMODE: "${FORCE_GAMEMODE:-false}"
      DIFFICULTY: "${DIFFICULTY:-easy}"
      ALLOW_CHEATS: "${ALLOW_CHEATS:-false}"
      MAX_PLAYERS: "${MAX_PLAYERS:-10}"
      ONLINE_MODE: "${ONLINE_MODE:-true}"
      ALLOW_LIST: "${ALLOW_LIST:-false}"
      ENABLE_BDS_V6BIND_FIX: "${ENABLE_BDS_V6BIND_FIX:-false}"
      SERVER_PORT: "19132" # do not override
      SERVER_PORT_V6: "19133" # do not override
      ENABLE_LAN_VISIBILITY: "${ENABLE_LAN_VISIBILITY:-true}"
      VIEW_DISTANCE: "${VIEW_DISTANCE:-32}"
      TICK_DISTANCE: "${TICK_DISTANCE:-4}"
      PLAYER_IDLE_TIMEOUT: "${PLAYER_IDLE_TIMEOUT:-30}"
      MAX_THREADS: "${MAX_THREADS:-8}"
      LEVEL_NAME: "${LEVEL_NAME:-world}"
      LEVEL_SEED: "${LEVEL_SEED:-}"
      LEVEL_TYPE: "${LEVEL_TYPE:-default}"
      DEFAULT_PLAYER_PERMISSION_LEVEL: "${DEFAULT_PLAYER_PERMISSION_LEVEL:-member}"
      TEXTUREPACK_REQUIRED: "${TEXTUREPACK_REQUIRED:-false}"
      CONTENT_LOG_FILE_ENABLED: "${CONTENT_LOG_FILE_ENABLED:-false}"
      CONTENT_LOG_LEVEL: "${CONTENT_LOG_LEVEL:-info}"
      CONTENT_LOG_CONSOLE_OUTPUT_ENABLED: "${CONTENT_LOG_CONSOLE_OUTPUT_ENABLED:-false}"
      COMPRESSION_THRESHOLD: "${COMPRESSION_THRESHOLD:-1}"
      COMPRESSION_ALGORITHM: "${COMPRESSION_ALGORITHM:-zlib}"
      SERVER_AUTHORITATIVE_MOVEMENT: "${SERVER_AUTHORITATIVE_MOVEMENT:-false}"
      PLAYER_POSITION_ACCEPTANCE_THRESHOLD: "${PLAYER_POSITION_ACCEPTANCE_THRESHOLD:-0.5}"
      PLAYER_MOVEMENT_SCORE_THRESHOLD: "${PLAYER_MOVEMENT_SCORE_THRESHOLD:-0.5}"
      PLAYER_MOVEMENT_ACTION_DIRECTION_THRESHOLD: "${PLAYER_MOVEMENT_ACTION_DIRECTION_THRESHOLD:-0.85}"
      PLAYER_MOVEMENT_DISTANCE_THRESHOLD: "${PLAYER_MOVEMENT_DISTANCE_THRESHOLD:-0.5}"
      PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: "${PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS:-1000}"
      CORRECT_PLAYER_MOVEMENT: "${CORRECT_PLAYER_MOVEMENT:-false}"
      SERVER_AUTHORITATIVE_BLOCK_BREAKING: "${SERVER_AUTHORITATIVE_BLOCK_BREAKING:-false}"
      SERVER_AUTHORITATIVE_BLOCK_BREAKING_PICK_RANGE_SCALAR: "${SERVER_AUTHORITATIVE_BLOCK_BREAKING_PICK_RANGE_SCALAR:-1.5}"
      CHAT_RESTRICTION: "${CHAT_RESTRICTION:-None}"
      DISABLE_PLAYER_INTERACTION: "${DISABLE_PLAYER_INTERACTION:-false}"
      CLIENT_SIDE_CHUNK_GENERATION_ENABLED: "${CLIENT_SIDE_CHUNK_GENERATION_ENABLED:-true}"
      BLOCK_NETWORK_IDS_ARE_HASHES: "${BLOCK_NETWORK_IDS_ARE_HASHES:-true}"
      DISABLE_PERSONA: "${DISABLE_PERSONA:-false}"
      DISABLE_CUSTOM_SKINS: "${DISABLE_CUSTOM_SKINS:-false}"
      SERVER_BUILD_RADIUS_RATIO: "${SERVER_BUILD_RADIUS_RATIO:-Disabled}"
      ALLOW_OUTBOUND_SCRIPT_DEBUGGING: "${ALLOW_OUTBOUND_SCRIPT_DEBUGGING:-false}"
      ALLOW_INBOUND_SCRIPT_DEBUGGING: "${ALLOW_INBOUND_SCRIPT_DEBUGGING:-false}"
      FORCE_INBOUND_DEBUG_PORT: "${FORCE_INBOUND_DEBUG_PORT:-false}"
      SCRIPT_DEBUGGER_AUTO_ATTACH: "${SCRIPT_DEBUGGER_AUTO_ATTACH:-disabled}"
      SCRIPT_DEBUGGER_AUTO_ATTACH_CONNECT_ADDRESS: "${SCRIPT_DEBUGGER_AUTO_ATTACH_CONNECT_ADDRESS:-}"
      SCRIPT_WATCHDOG_ENABLE: "${SCRIPT_WATCHDOG_ENABLE:-false}"
      SCRIPT_WATCHDOG_ENABLE_EXCEPTION_HANDLING: "${SCRIPT_WATCHDOG_ENABLE_EXCEPTION_HANDLING:-false}"
      SCRIPT_WATCHDOG_ENABLE_SHUTDOWN: "${SCRIPT_WATCHDOG_ENABLE_SHUTDOWN:-false}"
      SCRIPT_WATCHDOG_HANG_EXCEPTION: "${SCRIPT_WATCHDOG_HANG_EXCEPTION:-false}"
      SCRIPT_WATCHDOG_HANG_THRESHOLD: "${SCRIPT_WATCHDOG_HANG_THRESHOLD:-5000}"
      SCRIPT_WATCHDOG_SPIKE_THRESHOLD: "${SCRIPT_WATCHDOG_SPIKE_THRESHOLD:-1000}"
      SCRIPT_WATCHDOG_SLOW_THRESHOLD: "${SCRIPT_WATCHDOG_SLOW_THRESHOLD:-10}"
      SCRIPT_WATCHDOG_MEMORY_WARNING: "${SCRIPT_WATCHDOG_MEMORY_WARNING:-100}"
      SCRIPT_WATCHDOG_MEMORY_LIMIT: "${SCRIPT_WATCHDOG_MEMORY_LIMIT:-250}"

      OP_PERMISSION_LEVEL: "${OP_PERMISSION_LEVEL:-1}"
      # EMIT_SERVER_TELEMETRY: "${EMIT_SERVER_TELEMETRY:-false}"
      # MSA_GAMERTAGS_ONLY: "${MSA_GAMERTAGS_ONLY:-false}"
      # ITEM_TRANSACTION_LOGGING_ENABLED: "${ITEM_TRANSACTION_LOGGING_ENABLED:-false}"
      
      # VARIABLES: |
      #   var1=customStringValue
      #   var2=1234
      #   var3=true

      # ALLOW_LIST_USERS: |
      #   player1:1234567890
      #   player2:0987654321

      # OPS: |
      #   1234567890
      #   player1
      # MEMBERS: |
      #   player2
      # VISITORS: |
      #   player3
      #   player4

      MC_PACK: "/world/world.mcworld"
      # 3. Choose copy behavior:
      # - "false" (Recommended): Only imports the world on the very first startup.
      #   This ensures player progress is saved and not overwritten when the server restarts.
      # - "true": Resets the world back to the .mcworld state on EVERY restart.
      FORCE_WORLD_COPY: "${FORCE_WORLD_COPY:-false}"
      FORCE_PACK_COPY: "${FORCE_PACK_COPY:-false}"
      STOP_SERVER_ANNOUNCE_DELAY: "${STOP_SERVER_ANNOUNCE_DELAY:-10}"
      STOP_SERVER_ANNOUNCE: "${STOP_SERVER_ANNOUNCE:-say Server shutting down in %delay% seconds}"
    volumes:
      - mc_data:/data
      - ./world/world.mcworld:/world/world.mcworld
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  mc_data: